PREFIX c: <http://example.org/fi-tut-math-sm-calvin-and-hobbes/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

# Grouping: How many leafs the students have collected so far (in total)? 
# How many students are there?

# ON 2015

SELECT (SUM(?x) AS ?soFarCollected) (COUNT(?stud) AS ?nOfStudents)
WHERE {
  ?ba 
    a :Assignment ;
    :hasResults
      [ :hasPart [:student ?stud; :hasScore ?x] ] .
} GROUP by ?ba



